
spring:
  application:
    name: ordering-service
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ordering}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
server:
  port: ${SERVER_PORT:8080}
  use-forward-headers: true
  main.allow-bean-definition-overriding: true

app:
  rabbit:
    exchange: ${ORDERS_EXCHANGE:orders.exchange}
    queue: ${ORDER_CREATED_QUEUE:orders.created.queue}
    routing-key: ${ORDER_CREATED:orders.created}
  info:
    application_name: @project.name@
    version: @project.version@
    description: @project.description@
    artifact_Id: @project.artifactId@
    group_Id: @project.groupId@
    app_profile: ${ENVIRONMENT:dev}
    java-version: @java.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${HOSTNAME:localhost}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_SERVICE_PORT:8091}
  health:
    livenessState:
      enable: true
    readinessState:
      enable: true


logging:
  level:
    ru:
      sogaz:
        site:
          pattern: ${LOGGING_LEVEL_RU_SOGAZ_ESB:DEBUG}

logstash:
  host: ${LOG_SERVER_HOST:localhost}
  port: ${LOG_SERVER_PORT:12201}
  level: ${LOG_LEVEL:INFO}
  level_local: ${LOG_LEVEL_LOCAL:INFO}
